apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: dev
  labels:
    app: jenkins-app
spec:
  type: NodePort # Expose on a NodePort for Minikube access
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 # Access on <minikube_ip>:30000
      name: jenkins
  selector:
    app: jenkins-app
    tier: frontend
